<Style name="SwissWaysLow">
  <Rule>
    <LineSymbolizer stroke="#d30000" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" />
  </Rule>
</Style>

<Style name="SwissWaysMid">
  <Rule>
    <Filter>[network] = "AL1"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.7" />
  </Rule>
  <Rule>
    <Filter>[network] = "AL2"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-dasharray="8,3" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
  </Rule>
  <Rule>
    <Filter>[network] = "AL3"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-dasharray="4,3" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
  </Rule>
  <Rule>
    <Filter>[network] = "AL4"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-dasharray="2,2" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
  </Rule>
</Style>

<Style name="SwissWaysHigh">
  <Rule>
    <Filter>[network] = "AL1"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
  </Rule>
  <Rule>
    <Filter>[network] = "AL2"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-dasharray="8,3" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
  </Rule>
  <Rule>
    <Filter>[network] = "AL3"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-dasharray="4,3" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" />
  </Rule>
  <Rule>
    <Filter>[network] = "AL4"</Filter>
    <LineSymbolizer stroke="#d30000" stroke-dasharray="1,6" stroke-linecap="round" stroke-linejoin="round" stroke-width="3.0" />
  </Rule>
</Style>

