<Style name="Shields">
  <Rule>
    <ShieldSymbolizer base="syms" file="[fname].svg" placement="line" spacing="400" face-name="DejaVu Sans Mono Bold" label-position-tolerance="200" margin="20" repeat-distance="200"/>
  </Rule>
</Style>

<Style name="ShieldsLowZoom">
  <Rule>
    <ShieldSymbolizer base="syms" file="[fname].svg" face-name="DejaVu Sans Mono Bold" placement="line" margin="50" label-position-tolerance="100" spacing="200" repeat-distance="200" avoid-edges="true" />
  </Rule>
</Style>

