<Style name="Shields">
  <Rule>
    <ShieldSymbolizer base="syms" file="[fname].svg" placement="line" spacing="300" face-name="DejaVu Sans Mono Bold" label-position-tolerance="10 * [numshield]" margin="60" repeat-distance="400"/>
  </Rule>
</Style>

<Style name="ShieldsLowZoom">
  <Rule>
    <ShieldSymbolizer base="syms" file="[fname].svg" face-name="DejaVu Sans Mono Bold" placement="line" margin="50" spacing="200" repeat-distance="200" avoid-edges="true" />
  </Rule>
</Style>

