<Datasource name="psqlch">
    <Parameter name="type">postgis</Parameter>
    <Parameter name="port">5432</Parameter>
    <Parameter name="estimate_extent">false</Parameter>
    <Parameter name="extent">-20037508,-19929239,20037508,19929239</Parameter>
    <Parameter name="dbname">planet</Parameter>
    <Parameter name="geometry_field">geom</Parameter>
    <Parameter name="srid">3857</Parameter>
</Datasource>

